name: 30-minute-cron
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: curl --url 'https://wholesome-artists.vercel.app/api/'